<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="CA接口测试用例" duration-ms="49361" started-at="2019-09-26T17:59:40 CST" finished-at="2019-09-26T18:00:30 CST">
    <groups>
    </groups>
    <test name="说明：1 预期结果前面显法false_表示预期结果不是后面的值;2 用例描述中显示值为空时，表示参数值为空字符串" duration-ms="49361" started-at="2019-09-26T17:59:40 CST" finished-at="2019-09-26T18:00:30 CST">
      <class name="com.tsa.ra.testcase.RaTestCase">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:com.tsa.ra.testcase.RaTestCase@101952da]" name="beforeTest" is-config="true" duration-ms="31" started-at="2019-09-26T17:59:40 CST" finished-at="2019-09-26T17:59:40 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:com.tsa.ra.testcase.RaTestCase@101952da]" name="beforeClass" is-config="true" duration-ms="1" started-at="2019-09-26T17:59:40 CST" finished-at="2019-09-26T17:59:40 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="SKIP" signature="caTest(java.util.Map)[pri:0, instance:com.tsa.ra.testcase.RaTestCase@101952da]" name="caTest" duration-ms="0" started-at="2019-09-26T18:00:30 CST" data-provider="ra_ca_data" finished-at="2019-09-26T18:00:30 CST">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.io.IOException: Stream Closed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.io.IOException: Stream Closed
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:50)
at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:146)
at org.testng.internal.Parameters.handleParameters(Parameters.java:820)
at org.testng.internal.Parameters.handleParameters(Parameters.java:762)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:60)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:39)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:771)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.io.IOException: Stream Closed
at java.io.FileInputStream.readBytes(Native Method)
at java.io.FileInputStream.read(FileInputStream.java:255)
at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
at org.apache.poi.util.BoundedInputStream.read(BoundedInputStream.java:121)
at org.apache.poi.util.BoundedInputStream.read(BoundedInputStream.java:103)
at org.apache.poi.util.IOUtils.copy(IOUtils.java:400)
at org.apache.poi.util.IOUtils.peekFirstNBytes(IOUtils.java:78)
at org.apache.poi.util.IOUtils.peekFirst8Bytes(IOUtils.java:65)
at org.apache.poi.poifs.filesystem.FileMagic.valueOf(FileMagic.java:158)
at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:207)
at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:180)
at com.tsa.ra.utils.OperationExcel.readExData(OperationExcel.java:187)
at com.tsa.ra.dealdata.DealCaseData.getParamEnName(DealCaseData.java:17)
at com.tsa.ra.dealdata.GetMapParam.getParamKeyValue(GetMapParam.java:38)
at com.tsa.ra.dealdata.ExcelDataHeleper.dataMethod(ExcelDataHeleper.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:77)
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:46)
... 25 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- caTest -->
      </class> <!-- com.tsa.ra.testcase.RaTestCase -->
    </test> <!-- 说明：1 预期结果前面显法false_表示预期结果不是后面的值;2 用例描述中显示值为空时，表示参数值为空字符串 -->
  </suite> <!-- CA接口测试用例 -->
</testng-results>
